version: '3'
services:
  elastic0:
    image: youngbe/docker-swarm-elasticsearch:5.5.0
    container_name: elastic0
    environment:
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m -XX:-AssumeMP"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /vagrant/data/elastic0:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - esnet
    deploy:
      resources:
        limits:
          memory: 1g
          
  kibana:
    image: docker.elastic.co/kibana/kibana:5.5.0
    #image: kibana:5.4.3
    container_name: kibana
    restart: always
    networks:
      - esnet
    ports:
      - "5601:5601"
    external_links:
      - elastic0:elastic0
    depends_on:
      - elastic0
    environment:
      ELASTICSEARCH_URL: http://192.168.100.20:9200          
networks:
  esnet: